// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AdminLogin: typeof import('./src/components/AdminLogin.vue')['default']
    Question: typeof import('./src/components/Question.vue')['default']
    Sequence: typeof import('./src/components/Sequence.vue')['default']
    Settings: typeof import('./src/components/Settings.vue')['default']
    Spinner: typeof import('./src/components/Spinner.vue')['default']
  }
}

export { }
